spring.application.name=web2

spring.datasource.jdbc-url=jdbc:h2:mem:db_principal
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.audit.jdbc-url=jdbc:h2:mem:db_audit
spring.datasource.audit.driver-class-name=org.h2.Driver
spring.datasource.audit.username=sa
spring.datasource.audit.password=